### ISSUE TITLE
Unable to add torrent files

### ISSUE THREAD

**Issue by GHDiscard** [binhex/arch-delugevpn#152]
Hello, I'm a longtime user of deluge, but this is my first time trying this project.

I can click add, select a torrent file, and it shows as uploaded, but I can't click on it for more details, nor can I click add.

[Screenshot of what I see](http://images.resolve.me.uk/i/2019-12-23_15-12-44.png)
[Screenshot of what it would normally look like](http://images.resolve.me.uk/i/2019-12-23_15-12-22.png)

I've run a bash shell in the container, checked that the config and data directories are writable. I tried adjusting the data save directories to fall within /data/ instead of their default of /home/. I've tried deleting the container, all the attached folders, and doing nothing other than adding a vpn file.

Oddly it seems to work fine with magnet links from the limited testing I was able to do.

I've increased log verbosity, and watched deluged.log and deluge-web.log, but there was nothing useful there.

I've been checking the main deluge forums, and waiting to see if anything popped up here, but nothing has. Can anyone suggest what I might try next?

This is my docker-compose config:

```yaml
version: '3'

services:
  deluge:
    image: binhex/arch-delugevpn:latest
    container_name: deluge
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - nfs-deluge-data:/data
      - nfs-deluge-config:/config
      - /etc/localtime/:/etc/localtime:ro
    expose:
      - 8112
      - 8118
    ports:
      - 58846:58846
      - 58946:58946
    networks:
      - web
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=custom
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=no
      - LAN_NETWORK=10.10.1.1/24,192.168.0.1/24,172.19.0.0/16
      - NAME_SERVERS=8.8.8.8
      - DELUGE_DAEMON_LOG_LEVEL=debug
      - DELUGE_WEB_LOG_LEVEL=debug
      - DEBUG=true
      - UMASK=0000
      - PUID=0
      - PGID=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge-web.rule=Host('deluge.<removed>')"
      - "traefik.http.routers.deluge-web.entrypoints=web"
      - "traefik.http.routers.deluge-web.middlewares=web-default-chain@file"
      - "traefik.http.services.deluge-web.loadbalancer.server.port=8112"
      - "traefik.http.routers.deluge-web.service=deluge-web"
      - "traefik.http.routers.deluge-web-secure.rule=Host('deluge.<removed>')"
      - "traefik.http.routers.deluge-web-secure.entrypoints=web-secure"
      - "traefik.http.routers.deluge-web-secure.middlewares=web-secure-default-chain@file"
      - "traefik.http.routers.deluge-web-secure.tls=true"
      - "traefik.http.routers.deluge-web-secure.tls.certresolver=le"
      - "traefik.http.services.deluge-web-secure.loadbalancer.server.port=8112"
      - "traefik.http.routers.deluge-web-secure.service=deluge-web-secure"

volumes:
  nfs-deluge-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=rockstor.lab.<removed>,rw,nolock,vers=4
      device: ":/<removed>/deluge/config"
  nfs-deluge-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=rockstor.lab.<removed>,rw,nolock,vers=4
      device: ":/<removed>/deluge/downloads"

networks:
  mysql:
    external: true
  web:
    external:
      name: traefik
```
