### ISSUE TITLE
yarss2 broken again

### ISSUE THREAD

**Issue by nerfdaderp** [binhex/arch-delugevpn#299]
Anyone possibly know what might have broken yarss2 in the latest batch of releases? Running on a synology and I had the 3.8 python egg preivously. Tried 3.9 as well with no luck. Basically the checkbox can't be enabled when trying through the remote client and I'm not seeing anything logging side.

And maybe not the best place to ask, but are there any other options for bringing in RSS feeds?

**Comment by andreasd** [comment]
i'm having the same issue :-/

**Comment by nerfdaderp** [comment]
> i'm having the same issue :-/

After playing with it for a couple hours, I reverted back to an older image. It's pretty easy to do with portainer.

(I also misspoke above, I was using the 3.8 egg.)

**Comment by andreasd** [comment]
can you tell me which version you're using? i'm trying the same now and would be great if i would not have to try all different versions

**Comment by nerfdaderp** [comment]
Sure, I believe a couple of the future releases may work for you, but I rolled it back to: binhex/arch-delugevpn:2.0.4.dev56-g2e466101f-1-01

**Comment by andreasd** [comment]
thanks - got it to work with that version but ultimately dumped it and switched to flexget. maybe this helps somebody else:

setup a flexget container based on https://hub.docker.com/r/wiserain/flexget, then edited the config to support showrss and hand over the urls to deluge running in another container:

```
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  showrss-fetch:
    rss: http://showrss.info.... your url here!
    all_series: yes
    deluge:
      host: 10.0.0.100 # deluge url/ip
      port: 58846
      username: deluge
      password: deluge

schedules:
  - tasks: [showrss-fetch]
    interval:
      minutes: 30
```

this will check showrss every 30min for new shows and will then add new episodes to deluge.
