### ISSUE TITLE
Unable to access WebUI

### ISSUE THREAD

**Issue by lcdt22890158** [binhex/arch-delugevpn#337]
The container launches successfully, the logs indicate that it has connected to the VPN successfully and launched Deluge successfully. But I'm not able to access the Web UI, I just get "The connection has timed out".

I'm using TrueNAS with bhyve running a Ubuntu Server VM with Docker Swarm. My docker-compose.yml file looks like this:

```yaml
version: '3.8'
services:
  deluge:
    cap_add:
      - CAP_NET_ADMIN
    deploy:
      mode: replicated
      replicas: 1
    image: binhex/arch-delugevpn
    environment:
      - VPN_ENABLED=true
      - VPN_USER=myprotonusername
      - VPN_PASS=hunter2
      - VPN_PROV=custom
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARDING=no
      - ENABLE_PRIVOXY=no
      - LAN_NETWORK=192.168.10.240/24
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=debug
      - DEBUG=true
      - PUID=1003
      - PGID=1004
    volumes:
      - /mnt/nas/working/deluge/config:/config
      - /mnt/nas/working/deluge:/data
    ports:
      - 8112:8112
      - 58846:58846
      - 58946:58946
```

Log files:

 - [supervisord.log](https://pastebin.com/Tg1YxAAc)

 - [deluge-web.log](https://pastebin.com/J0EKZ3cQ)

But when I access `http://192.168.10.240:8112` the connection times out.

ProtonVPN doesn't currently support port forwarding on non-Windows platforms, so I've got STRICT_PORT_FORWARDING disabled. I also tried having `LAN_NETWORK` set to 192.168.10.0/24 with the same result. I tried configuring the Docker port as `9094:8112` and accessing `http://192.168.10.240:9094` as well, also no luck.

I'm able to access other containers running on the same node (such as pyMedusa and Jackett) without any issues.
