### ISSUE TITLE
Support for Custom Docker Network built-in DNS server (and named container resolving)

### ISSUE THREAD

**Issue by alexmerm** [binhex/arch-delugevpn#399]
Would be nice to have the option to include the custom docker network dns as a nameserver. Would enable accessing other containers on the same custom network thru their name. Currently requires the direct IP of other containers which is hard to obtain. 
An example compose file would look like:
```
services:
    arch-delugevpn:
        cap_add:
            - NET_ADMIN
        ports:
            - '8112:8112'
            - '8118:8118'
            - '58846:58846'
            - '58946:58946'
        container_name: delugevpn
        ...
        image: 'binhex/arch-delugevpn:latest'
    sonarr:
        ...
        ports:
          - 8989:8989
        restart: unless-stopped
```
Currently, within other containers you can access deluge at "http://delugevpn:8112", this would allow access from deluge container to sonarr via "http://sonarr:8989"
