### ISSUE TITLE
OpenVPN creates an infinite loop

### ISSUE THREAD

**Issue by C0RR1T** [binhex/arch-delugevpn#403]
My Docker container shows the following error over and over again:
```
deluge    | 2024-06-25 00:53:02,042 DEBG 'start-script' stdout output:
deluge    | [info] Starting OpenVPN (non daemonised)...
deluge    |
deluge    | 2024-06-25 00:53:02,048 DEBG 'start-script' stdout output:
deluge    | 2024-06-25 00:53:02 DEPRECATED OPTION: --cipher set to 'aes-128-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305). OpenVPN ignores --cipher for cipher negotiations.
deluge    | 2024-06-25 00:53:02 OpenVPN 2.6.10 [git:makepkg/ba0f62fb950c56a0+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO] built on Mar 20 2024
deluge    | 2024-06-25 00:53:02 library versions: OpenSSL 3.3.1 4 Jun 2024, LZO 2.10
deluge    | 2024-06-25 00:53:02 DCO version: N/A
deluge    |
deluge    | 2024-06-25 00:53:02,048 DEBG 'start-script' stdout output:
deluge    | 2024-06-25 00:53:02 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
deluge    | 2024-06-25 00:53:02 Exiting due to fatal error
deluge    |
deluge    | 2024-06-25 00:53:02,050 DEBG 'start-script' stdout output:
deluge    | [info] Starting OpenVPN (non daemonised)...
```
I want to use Deluge with PIA, so I configured the docker compose like below:
```yaml
  # Torrent
  deluge:
    container_name: deluge
    restart: unless-stopped
    environment:
      - VPN_ENABLED=yes
      - VPN_USER={user}
      - VPN_PASSWORD={pass}
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - ENABLE_STARTUP_SCRIPTS=no
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=yes
      - SOCKS_USER={sock_user}
      - SOCKS_PASS={sock_pass}
      - PUID=0
      - PGID=0
      - UMASK=000
      - DEBUG=false
      - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_ENABLE_WEBUI_PASSWORD=yes
      - LAN_NETWORK=192.168.1.0/24
    cap_add: ["NET_ADMIN"]
    image: binhex/arch-delugevpn:latest
    volumes:
      - ~/deluge/config:/config
      - ~/media/download:/download
      - /etc/localtime:/etc/localtime:ro
      - ~/deluge/data:/data
    networks:
      - proxy-network
```
